name = pae_arsip
title = PAE - Pengelolaan Arsip Elektronik
description = Media pembelajaran interaktif Pengelolaan Arsip Elektronik (PAE). Misi 1: Pengumpulan Bahan Arsip.
depends =
optional_depends = default, character
author = JatnikoNM
release = 2
